searches:
  - name: data_engineer_orlando
    keyword: "data engineer"
    location: "Orlando, FL"

  - name: data_analyst_orlando
    keyword: "data analyst"
    location: "Orlando, FL"

  - name: data_scientist_orlando
    keyword: "data scientist"
    location: "Orlando, FL"
  
  - name: cloud_engineer_orlando
    keyword: "cloud engineer"
    location: "Orlando, FL"

  - name: data_engineer_dc
    keyword: "data engineer"
    location: "Washington, DC"
  
  - name: data_analyst_dc
    keyword: "data analyst"
    location: "Washington, DC"
  
  - name: data_engineer_atl
    keyword: "data engineer"
    location: "Atlanta, GA"

  - name: data_engineer_seattle
    keyword: "data engineer"
    location: "Seattle, WA"

  - name: data_management_dc
    keyword: "data management"
    location: "Washington, DC"